package ru.hse.se.team9.game.entities.map

import arrow.core.Either
import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.JsonSerializer
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import ru.hse.se.team9.entities.EmptySpace
import ru.hse.se.team9.entities.MapObject
import ru.hse.se.team9.entities.Wall
import ru.hse.se.team9.game.entities.map.distance.Distance
import ru.hse.se.team9.game.entities.map.distance.Manhattan
import ru.hse.se.team9.game.entities.map.objects.HeroOnMap
import ru.hse.se.team9.game.entities.map.objects.MobOnMap
import ru.hse.se.team9.game.entities.mobs.strategies.MobStrategy
import ru.hse.se.team9.game.entities.mobs.strategies.PassiveStrategy
import ru.hse.se.team9.game.entities.mobs.strategies.RandomStrategy
import ru.hse.se.team9.model.random.directions.DirectionGenerator
import ru.hse.se.team9.model.random.directions.RandomDirection
import ru.hse.se.team9.model.random.positions.PositionGenerator
import ru.hse.se.team9.positions.Position
import ru.hse.se.team9.utils.getRandomNotWallPosition
import ru.hse.se.team9.utils.plus

/** Represents game map
 * @property hero hero and its position on map
 * @property map two-dimensional array of MapObject, stores landscape elements and not active participants of game
 * @property width width of map
 * @property height height of map
 * @property positionGenerator object using for generating random positions on map
 */
class GameMap(
    val hero: HeroOnMap,
    val map: List<MutableList<MapObject>>,
    val width: Int,
    val height: Int,
    private val positionGenerator: PositionGenerator,
    val mobs: List<MobOnMap>,
    val distance: Distance,
    val fogRadius: Int
) {
    val fog = FogOfWar(distance, map, width, height, fogRadius)

    init {
        fog.updateVision(hero.position)
    }

    /** Moves hero to the given position. If map has wall at this position, does nothing
     * @param newPosition position to move hero to
     */
    fun moveHero(newPosition: Position) {
        if (canMoveTo(newPosition)) {
            hero.position = newPosition
        }
    }

    /** Moves hero to the neighbor cell according to the direction. If map has wall at this position, does nothing.
     * @param direction direction to move towards
     */
    fun moveHero(direction: Direction) {
        val position = hero.position + direction
        if (canMoveTo(position)) {
            hero.position = position
            fog.updateVision(position)
        }
    }

    fun moveMob(mobOnMap: MobOnMap, newPosition: Position) {
        for (mob in mobs) {
            if (mobOnMap == mob) {
                if (canMoveTo(newPosition)) {
                    mob.position = newPosition
                }
            }
        }
    }

    fun placeAtRandomPosition(mapObject: MapObject) {
        val (x, y) = getRandomNotWallPosition(positionGenerator, map)
        map[y][x] = mapObject
    }

    private fun isOnMap(position: Position): Boolean {
        val (x, y) = position
        return x >= 0 && y >= 0 && x < width && y < height
    }

    private fun isNotWall(position: Position): Boolean {
        val (x, y) = position
        return map[y][x] !is Wall
    }

    private fun canMoveTo(position: Position): Boolean {
        return isOnMap(position) && isNotWall(position)
    }

    /** Writes this map object as string */
    fun serialize(): String = mapper.writeValueAsString(this)

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as GameMap

        if (hero != other.hero) return false
        if (map != other.map) return false
        if (width != other.width) return false
        if (height != other.height) return false
        if (positionGenerator != other.positionGenerator) return false

        return true
    }

    override fun hashCode(): Int {
        var result = hero.hashCode()
        result = 31 * result + map.hashCode()
        result = 31 * result + width
        result = 31 * result + height
        result = 31 * result + positionGenerator.hashCode()
        return result
    }

    // TODO need A LOT OF fixes
    companion object Serialization {
        /**
         * Reads map from string and puts specified positionGenerator in it.
         * Accepts strings which were generated by GameMap::serialize method.
         */
        fun deserialize(
            string: String,
            positionGenerator: PositionGenerator
        ): Either<Throwable, GameMap> {
            return try {
                val gameMap = mapper.readValue<DeserializedGameMap>(string)
                Either.right(
                    GameMap(
                        gameMap.hero,
                        gameMap.map,
                        gameMap.width,
                        gameMap.height,
                        positionGenerator,
                        gameMap.mobs,
                        Manhattan,
                        gameMap.fogRadius
                    )
                )
            } catch (e: Throwable) {
                Either.left(e)
            }
        }

        private val mapper = jacksonObjectMapper().registerModule(SimpleModule().apply {
            addSerializer(GameMap::class.java, GameMapSerializer())
            addSerializer(MapObject::class.java, MapObjectSerializer())
            addDeserializer(MapObject::class.java, MapObjectDeserializer())
            addSerializer(MobStrategy::class.java, StrategySerializer())
            addDeserializer(MobStrategy::class.java, StrategyDeserializer(RandomDirection)) // TODO fix
//            addSerializer(Distance::class.java, DistanceSerializer())
//            addDeserializer(Distance::class.java, DistanceDeserializer())
        })

        /*class DistanceDeserializer : JsonDeserializer<Distance>() {
            override fun deserialize(p: JsonParser, ctxt: DeserializationContext): Distance {
                return when (val str = p.valueAsString) {
                    "M" -> Manhattan
                    "D" -> Descartes
                    else -> ctxt.handleWeirdStringValue(
                        Distance::class.java,
                        str,
                        "cannot deserialize map object"
                    ) as Distance
                }
            }

        }

        class DistanceSerializer : JsonSerializer<Distance>() {
            override fun serialize(value: Distance, gen: JsonGenerator, serializers: SerializerProvider) {
                when (value) {
                    is Manhattan -> gen.writeString("M")
                    is Descartes -> gen.writeString("D")
                }
            }
        }*/


        private data class DeserializedGameMap(
            val hero: HeroOnMap,
            val map: List<MutableList<MapObject>>,
            val width: Int,
            val height: Int,
            val mobs: List<MobOnMap>,
            val fogRadius: Int
        )

        private class GameMapSerializer : JsonSerializer<GameMap>() {
            override fun serialize(value: GameMap, gen: JsonGenerator, serializers: SerializerProvider) {
                gen.writeStartObject()
                gen.writeObjectField("hero", value.hero)
                gen.writeNumberField("width", value.width)
                gen.writeNumberField("height", value.height)
                gen.writeObjectField("map", value.map)
                gen.writeObjectField("mobs", value.mobs)
                //gen.writeObjectField("distance", value.distance)
                gen.writeNumberField("fogRadius", value.fogRadius)
                gen.writeEndObject()
            }
        }

        // TODO fix
        private class StrategyDeserializer(
            val directionGenerator: DirectionGenerator
        ) : JsonDeserializer<MobStrategy>() {
            override fun deserialize(p: JsonParser, ctxt: DeserializationContext): MobStrategy {
                return when (val str = p.valueAsString) {
                    "R" -> RandomStrategy(directionGenerator)
                    "P" -> PassiveStrategy
                    else -> ctxt.handleWeirdStringValue(
                        MobStrategy::class.java,
                        str,
                        "cannot deserialize map object"
                    ) as MobStrategy
                }
            }
        }

        private class StrategySerializer : JsonSerializer<MobStrategy>() {
            override fun serialize(value: MobStrategy, gen: JsonGenerator, serializers: SerializerProvider) {
                when (value) {
                    is RandomStrategy -> gen.writeString("R")
                    is PassiveStrategy -> gen.writeString("P")
                }
            }
        }

        private class MapObjectSerializer : JsonSerializer<MapObject>() {
            override fun serialize(value: MapObject, gen: JsonGenerator, serializers: SerializerProvider) {
                when (value) {
                    is EmptySpace -> gen.writeString(".")
                    is Wall -> gen.writeString("@")
                }
            }
        }

        private class MapObjectDeserializer : JsonDeserializer<MapObject>() {
            override fun deserialize(p: JsonParser, ctxt: DeserializationContext): MapObject? {
                return when (val str = p.valueAsString) {
                    "." -> EmptySpace
                    "@" -> Wall
                    else -> ctxt.handleWeirdStringValue(
                        MapObject::class.java,
                        str,
                        "cannot deserialize map object"
                    ) as MapObject
                }
            }
        }
    }
}